### ISSUE TITLE
Compatibility with Emacs (Cider)

### ISSUE THREAD

**Issue by JAremko** [tengstrand/lein-polylith#15]
symbolic links in source sub-folders have an issue with Emacs and Cider https://github.com/clojure-emacs/cider/issues/2505

*for the reference*

**Comment by furkan3ayraktar** [comment]
Thanks Eugene for letting us know that [Cider](https://github.com/clojure-emacs/cider) does not support symbolic links. We've tested Polylith with [Cursive](https://cursive-ide.com) and it is my recommendation to go forward for now. I'll be following the issue in cider repository.

I'm closing the issue because we can't do anything from Polylith side. Let me know if we can help with anything.
