### ISSUE TITLE
DRYing interface documentation

### ISSUE THREAD

**Issue by JAremko** [tengstrand/lein-polylith#30]
### Context:
I have functions in my components that in addition to doc-strings use [orchestra](https://github.com/jeaye/orchestra) for specing arguments and return values.

Example from orchestra:
``` clojure
(defn-spec my-add integer?
  "Returns the sum of `a` and `b`."
  [a integer?, b integer?]
  (+ a b))
```

I also want to document my interface files.  Mainly because my IDE (Emacs) can display doc-strings/specs for symbols but also documenting public interface of a component seems like a right thing to do instead of making people dig inside component's guts for clues.

### The problem:
I'll have to copy doc-strings and the `defn-spec` signatures into my interface files and manually ensure that they are synchronized, that doc-strings in interfaces don't go stale, etc. On top of this i'll have to import `orchestra` and spec predicates used in `defn-spec`s into interface namespaces. 

Obviously expecting that `lein-polylith` will handle third party macroses like `defn-spec` isn't realistic.

### Potential solution:

Polylith can provide a hook for `lein polylith sync` calls in form of multi-method that can be used to register symbols like `defn-spec` ->  "interface generator method".
The methods will be defined by end-users to generate corresponding interface file entry and even keep the entry in sync with the components internal `defn-spec`. It will solve the problem in extensible way. 

Also it can be helpful if end-user will be able to control (in multi-method calls) whether an internal component symbol should be promoted into corresponding interface file with next sync without any other component using it (yet). Personally I'll be happy to use some kind of meta on my defn-spec definitions. Mb someone will choose to go with all public functions or even use some kind of custom manifest file :thinking: 

Adding extra imports like `defn-spec` macro into each interface `ns` can be handled similarly or via some kind of template/parameter that will be read  during component creation.

**Comment by furkan3ayraktar** [comment]
Hi @JAremko 

Thanks for the issue. First of all, I haven't used `orchestra` before in my projects, so let me know if I interpreted something in a wrong way.

Since Polylith uses the `workspace interfaces` only to validate that all of the components are using other components via their interfaces. Those workspace interfaces are never used in any other place, not in development, production, or REPL. Because of that, adding spec to workspace interfaces won't do anything. I would suggest to keep your spec definitions inside the components and try to keep `workspace interfaces` as empty as possible.

**Comment by JAremko** [comment]
@furkan3ayraktar  No i'm talking about component interfaces. like [this one](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/develop/components/article/src/clojure/realworld/article/interface.clj) they are [imported directly](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/develop/bases/rest-api/src/clojure/realworld/rest_api/handler.clj#L2) but definitions (wrappers) in them lack docs/specs etc.

**Comment by JAremko** [comment]
For example:
``` clojure
(defn article [auth-user slug] (core/article auth-user slug))
````
 Will have to be manually rewritten(and kept in sync) into:

``` clojure
(defn-spec article vector?
"My doc string"
[auth-user string? slug string?] 
(core/article auth-user slug))
```

- - - - - - - - -

So I'm thinking. Mb it is possible to introducing a way to promote custom definitions into component interfaces automatically :thinking:

**Comment by furkan3ayraktar** [comment]
I kinda understand your use case, please correct me if I'm wrong. 

The `defn-spec` macro of orchestra actually expands to a `defn` and a `spec/fdef`. And you do not want to write `defn` and `fdef` separately, as explained [here](https://clojure.org/guides/spec#_specing_functions). When you use the macro, Polylith tool can’t find a `defn` in the `component interface` that corresponds to a `defn` in `workspace interface`.

If Polylith tool compared component and workspace interfaces after the macro expands, there wouldn’t be a problem. Since it compares them by just reading the source files, it can't match them.

(1) So ideally the following should work:

`interfaces/src/com/test/comp1/interface.clj`
```clojure
(defn foo [arg1 arg2])
```

`components/comp1/src/com/test/comp1/interface.clj`
```clojure
(defn-spec foo int?
  "A foo function"
  [arg1 int? arg2 int?]
  (core/foo arg1 arg2))
```

(2) Since Polylith tool compares those two files by looking at the source files, currently it expects following:

`interfaces/src/com/test/comp1/interface.clj`
```clojure
(defn foo [arg1 arg2])
```

`components/comp1/src/com/test/comp1/interface.clj`
```clojure
(defn foo
  "A foo function"
  [arg1 arg2]
  (core/foo arg1 arg2))

(spec/fdef foo
  :args (s/cat :arg1 int? :arg2 int?)
  :ret int?)
```

I'm not sure if the necessary functionality in Polylith tool is letting tool know which macros it should accept. In that case, if you would add `(defn-spec ...)` to both interfaces and tell Polylith tool to consider `defn-spec` while comparing, you would need to add that dependency to the `interfaces` project, which makes things even more complicated.

Maybe the approach should be expanding macros in the `component interface` before comparing it with `workspace interface`. In this case the option (1) would work.

**Comment by JAremko** [comment]
@furkan3ayraktar 

> If Polylith tool compared component and workspace interfaces after the macro expands, there wouldn’t be a problem. Since it compares them by just reading the source files, it can't match them.

It may work in the `defn-spec` case but it will not work if the macro needs to be expanded to the custom level. LIke if `defn-spec` expanded into something that also must be expanded one more time but not totally since we want to preserve `defn`s

Also in the case of ` defn-spec` only "side effect" is `fdef` but some other macroses may generate extra `def`s and `defn`s  (for tooling/debugging) that end up cluttering workspace interfaces :thinking:

**Comment by JAremko** [comment]
Another big problem is keeping `defn-spec` in a component interface synced with the one in the component's implementation. I imagine it is extremely easy to forget to updating interface's doc-string or specs after component refactoring.
Even with `defn`s I sometime forget to rename arguments (after renaming them in component's implementation)
Mb polylith can help with this somehow :thinking:   For example,  sync(in verbose mode?) can warn when an interface's `defn` is a simple wrapper around component's `defn`  but argument names/arity mismatchs. And can it be customizable enough to help with keeping `defn-spec` synced  :thinking:
