### ISSUE TITLE
coveralls.io source-code view support

### ISSUE THREAD

**Issue by JAremko** [tengstrand/lein-polylith#31]
https://coveralls.io  needs access to source code files at github to display coverage. 
Unfortunately it doesn't work with symlinks.

Can polylith provide a wrapper for [cloverage](https://github.com/cloverage/cloverage) to fix file paths in the coverage report that gets uploaded to https://coveralls.io?

**Comment by JAremko** [comment]
I hack together  [this script](https://github.com/JAremko/spacetools/blob/7cd872ac57c4110698bfb9a48bbd4e7ad9a5ce34/scripts/coveralls/fix-paths.clj) seems to work fine(I can [preview coverage](https://coveralls.io/builds/21635669/source?filename=/components/spacedoc-io/src/spacetools/spacedoc_io/core.clj) now) but more standardized solution would be great.

**Comment by furkan3ayraktar** [comment]
Hi @JAremko 

I think since this is pretty specific to a tool of your choice, it's better to use a script that helps you to use the tool within your project's context, instead of adding it directly to Polylith. 

We are also working on a refactoring plan for Polylith Plugin to make it more extendable. This refactor will aim to let the community to develop around the Polylith core, support more build tools (boot, tools.deps, etc.), add support for specific use cases etc. You can refer to last comment in [this thread](https://polylith.freeflarum.com/d/12-the-troubles-with-symlinks-and-an-alternative-solution/13) on Polylith forum.

**Comment by JAremko** [comment]
@furkan3ayraktar  https://codecov.io/ works fine with symlinks. 
It may be Worthwhile to mention this in docs.
