### ISSUE TITLE
 Could not create symbolic link 

### ISSUE THREAD

**Issue by 956237586** [tengstrand/lein-polylith#37]
Warning. Could not make file executable 'D:\lein\example\systems\cmd-line\build.sh':
Warning. Could not create symbolic link 'D:\lein\example/environments/D:\lein\example\environments\development/docs/cmd-line-readme.md': Illegal char <:> at index 36: D:\lein\example\environments\D:\lein\example\environments\development\docs\cmd-line-readme.md

**Comment by 956237586** [comment]
doesn't support windows?

**Comment by furkan3ayraktar** [comment]
Hi, in order to use polylith with Microsoft Windows, you need to use _Windows Subsystem for Linux_. You can find detailed information about it [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10). The reason we require this is Windows does not support symbolic links out of the box and current version of Polylith heavily depends on symbolic links.

**Comment by mukulashokjoshi** [comment]
Just a note for anyone else trying to use polylith on Windows, it is possible to create symbolic links using cygwin
