### ISSUE TITLE
Creating system does not create link to base testing code

### ISSUE THREAD

**Issue by paulrd** [tengstrand/lein-polylith#4]
**Describe the bug**
When a new system is created, there should be a test directory created along with a source directory. This directory is not created.

**To Reproduce**
1. Follow the example in the README
2. Run ```lein polylith create s cmd-line cmd-line```
3. Notice that no test directory exists in the system/cmd-line directory

**Expected behavior**
There should be a system/cmd-line directory as described in the README:
"...with its corresponding test systems/cmd-line/test/se/example/cmd_line/core_test.clj:"

**Operating System (please complete the following information):**
 - OS: Linux Ubuntu 10.04.1

**Versions (please complete the following information):**

- Leiningen 2.8.1 on Java 10.0.2 OpenJDK 64-Bit Server VM
 - Polylith: 0.1.1

**Comment by tengstrand** [comment]
Hi!
You can find the test in `bases/cmd-line/test/se/example/cmd_line/core_test.clj`.
I need to update the documentation, thanks for spotting that! 
Besides that, everything works as it should.

To explain this I want you to execute this from the *workspace* root:
```
$ cd systems/cmd-line/src/se/example
$ ls -l
```
This will list:
```
address -> ../../../../../components/address/src/se/example/address
cmd_line -> ../../../../../bases/cmd-line/src/se/example/cmd_line
user -> ../../../../../components/user/src/se/example/user
```
As you can see, the `src` directory is just a set of symbolic links to the `cmd-line` _base_ and two more _components_.

*Systems* only contain a `src` directory and no `test` directory by default. If you list the files under `systems/cmd-line` you will find a `src` directory but no `test` directory.

In Polylith, the code in each *system* only serve the purpose to build a deployable artefact, that's why they don't need a `test` folder.

*Systems* are tested from the development *environment*  by executing the corresponding *base* used by each *system*. Each *base* will automatically "connect" with the *components* that matches the *interface* in the development *environment* (an *environment* can only have one *component* per *interface*).

If you want to test your *systems* through the *systems* itself, then you need to manually add a `test` directory and put the tests there. A reason for adding tests to a *system* could be that you want to execute End-to-End tests.

If you do that, note that you also need to manually execute the tests from your CI build. They are not managed by the plugin (they probably need special setup/treatment anyway).
